services:  
  metaapi:
    image: developergeralt/gamestore.api.meta
    container_name: gamestore.api.meta
    ports:
      - "2016:2016"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:2016"
    networks:
      - appnet

networks:
  appnet:
    external: true
