services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: gamestore.db.mongodb
    ports:
      - "27000:27017"
    networks:
      - appnet
    volumes:
      - mongo_data:/data/db

networks:
  appnet:
    external: true

volumes:
  mongo_data:
